name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app with Vite
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }} 
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }} 
        run: |
          npm run build 

      - name: Configure AWS Credentials for S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: eu-north-1 

      - name: Deploy to S3
        run: |
          echo "Starting synchronization of 'dist/' to S3://${{ secrets.S3_BUCKET_NAME }}"
          # Deploys the contents of the 'dist/' folder to S3
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete 
          echo "Deployment complete to S3://${{ secrets.S3_BUCKET_NAME }}"
